// Regenerates fonts.js from the .woff2 files in fonts/. The app loads fonts as
// data so they also work from a downloaded copy opened as a file, and so
// exports can embed exactly the fonts they use.
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const families = {
  'bangers': 'Bangers',
  'comic-neue': 'Comic Neue',
  'patrick-hand': 'Patrick Hand',
  'permanent-marker': 'Permanent Marker'
};
const latin = 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD';

const faces = fs.readdirSync(path.join(root, 'fonts')).filter((file) => file.endsWith('.woff2')).sort().map((file) => {
  const match = file.match(/^(.+)-latin-(\d+)-(normal|italic)\.woff2$/);
  if (!match || !families[match[1]]) throw new Error(`Unexpected font file: ${file}`);
  return {
    family: families[match[1]],
    weight: match[2],
    style: match[3],
    unicodeRange: latin,
    data: fs.readFileSync(path.join(root, 'fonts', file)).toString('base64')
  };
});

const output = `// Generated by tools/build-fonts.cjs from fonts/. Do not edit by hand.
// Licences and sources: fonts/README.md.
window.SpeechbubbleFonts = ${JSON.stringify(faces, null, 1)};
`;
fs.writeFileSync(path.join(root, 'fonts.js'), output);
console.log(`fonts.js: ${faces.length} faces, ${Math.round(output.length / 1024)} KB`);
